version: "2.4"

services:
  shimakaze-consumer:
    container_name: shimakaze-consumer
    image: rl404/shimakaze:latest
    command: ./shimakaze consumer
    restart: always
    env_file: ./../.env
    network_mode: host
